[project]
authors = [{name = "Chen Peng", email = "chen56@msn.com"}]
dependencies = [
    "deepdiff>=8.6.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "plotly>=6.5.1",
    "pydantic>=2.12.5",
    "quarto>=0.1.0",
    "rich>=14.2.0",
    "shiny>=1.5.1",
]
name = "study-quarto"
requires-python = ">= 3.12"
version = "0.0.1"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
# uv_build默认就使用 src/ 布局，不需要额外配置
build-backend = "uv_build"


[tool.uv.build-backend]
module-root = "."

[tool.uv]
# workspace 根虽然没代码，但作为聚合包
package = false
